### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xypron** [afaerber/meson-tools#1]
@afaerber 

Currently it is unclear if your code is open source. Could you, please, add a license file.

Best regards

Heinrich Schuchardt

**Comment by afaerber** [comment]
Good point, none of the source files have a proper header yet.

For the data structures I'd like to use MIT for maximum reuse. For the actual tool I would tend towards GPL-2.0+. Would that work for you, or do you have other suggestions?

**Comment by xypron** [comment]
Hello @afaerber,

I am fine with GPL. U-Boot is GPL-2.0 anyway.

In https://github.com/xypron/kernel-odroid-c2 I am using your code to build U-Boot with MMC support for the Odroid C2.

Please, also have a look at my pull request.

Best regards

Heinrich Schuchardt

**Comment by afaerber** [comment]
Thanks again for reminding of this. I added simple headers with SPDX identifiers to all source files, as well as a GPL-2.0 COPYING file.
