### ISSUE TITLE
g12 support required

### ISSUE THREAD

**Issue by matwey** [afaerber/meson-tools#9]
It would be great to support Odroid C4 based on S905X3 (g12)

**Comment by angerman** [comment]
@matwey does https://github.com/angerman/meson64-tools do, what you need?

**Comment by matwey** [comment]
I didn't know about this! Thank you. I'll check later.

**Comment by superna9999** [comment]
@matwey it's done in https://github.com/repk/gxlimg

**Comment by matwey** [comment]
@superna9999 thanks, I've already found it, but I could not make it boot Odroid-C4 yes
